### PR TITLE
Make administrate dependency less restrictive

### PR DESCRIPTION
**Pull request by pedantic-git**
Administrate is on version 0.3.0 now, so this plugin won't install on the latest version without a less restrictive version check.

That said, after updating I can't get the ckeditor fields to appear without manually calling `CKEDITOR.replace` - any idea why?

### CODE REVIEW

**Comment by pedantic-git** [comment]
Oh I see, it's because administrate loads the ckeditor code at the end and that's after the inserted <script> tags have executed. Let me look for a way around that before you accept this PR.

**Comment by rikkipitt** [comment]
@pedantic-git, yep that's the problem. I was going to move the script call in Administrate to the head and see if they'd accept the pull request... Not had a chance to do so yet.

**Comment by pedantic-git** [comment]
It's funny that it was working before, but it's always been at the end in administrate. I guess maybe it's the ckeditor gem that's changed?

**Comment by pedantic-git** [comment]
OK - I've put a workaround in which lifts some of the code from the Ckeditor gem and puts it in a content_for(:javascript). I think the "true" fix is probably to update the Ckeditor gem to allow it to insert the JavaScript part in a place of your choice, rather than directly below the field. But this will do for me for now!

**Comment by rikkipitt** [comment]
Hi @pedantic-git I'll check this out and get back to you after I've given it all a quick test!

Thanks for your help on this.

**Comment by rikkipitt** [comment]
@pedantic-git thanks for your work on this. I've merged the work of @x1024 which was a similar fix but seemed slightly less complex. If you use version 0.0.4, you'll be able to use the gem again.

Cheers both for all your help!

Rikki

**Comment by pedantic-git** [comment]
Ooh that is clever with the monkeypatching!

@x1024 - have you also got a PR to load this into the ckeditor gem itself, making your monkeypatch redundant?

**Pull request closed without merging**
