### PR TITLE
Add support for 0.4

### PR DESCRIPTION
**Pull request by pedantic-git**
I've tested and everything seems to work with the newer version of administrate - it just needs the gemspec bumping.

### CODE REVIEW

**Comment by rikkipitt** [comment]
@pedantic-git Cheers Rich, as always thanks for your help maintaining this plugin!

**Comment by pedantic-git** [comment]
@rikkipitt No worries! It's a great plugin and administrate is back to being quite the moving target!

**Comment by rikkipitt** [comment]
@pedantic-git It seems that way! They went quiet for a little while but seem to have it back in active development.

I'll release a new version of this plugin later today, otherwise, just use the master in your Gemfile if you need this sooner.

**Comment by rikkipitt** [comment]
New version released to RubyGems!

**Comment by pedantic-git** [comment]
Cheers!

**Pull request merged**
